"use client";

import { Download, FileText, Printer } from "lucide-react";

import { Button } from "@/components/ui/button";
import { formatCurrency } from "@/lib/currency";
import type { CurrencyCode, ForecastMode, ForecastResult, MonthEntry } from "@/lib/types";
import { useToast } from "@/hooks/use-toast";

interface ExportButtonsProps {
  entries: MonthEntry[];
  result: ForecastResult;
  currency: CurrencyCode;
  mode: ForecastMode;
}

export function ExportButtons({ entries, result, currency, mode }: ExportButtonsProps) {
  const { toast } = useToast();

  const rows = [
    ...entries.map((e) => ({ month: e.month, type: "Actual", amount: e.amount })),
    ...result.predictions.map((p) => ({ month: p.month, type: "Forecast", amount: p.amount })),
  ];

  const handleCsv = () => {
    const header = ["Month", "Type", `Amount (${currency})`];
    const csvRows = [
      header.join(","),
      ...rows.map((r) => [r.month, r.type, r.amount.toFixed(2)].join(",")),
    ];
    const blob = new Blob([csvRows.join("\n")], { type: "text/csv;charset=utf-8;" });
    downloadBlob(blob, `${mode}-forecast.csv`);
    toast({ title: "CSV exported", description: "Your forecast was downloaded as a .csv file." });
  };

  const handlePdf = async () => {
    try {
      const { default: jsPDF } = await import("jspdf");
      const autoTableModule = await import("jspdf-autotable");
      const autoTable = autoTableModule.default;

      const doc = new jsPDF();
      const title = `${mode === "profit" ? "Profit" : "Expense"} Forecast`;

      doc.setFontSize(18);
      doc.text(title, 14, 20);

      doc.setFontSize(10);
      doc.setTextColor(100);
      doc.text(
        `Generated by Ledgerline · ${new Date().toLocaleDateString()}`,
        14,
        27
      );

      autoTable(doc, {
        startY: 34,
        head: [["Month", "Type", `Amount (${currency})`]],
        body: rows.map((r) => [r.month, r.type, formatCurrency(r.amount, currency)]),
        headStyles: { fillColor: [52, 211, 153] },
        styles: { fontSize: 10 },
      });

      const finalY = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY;

      doc.setFontSize(11);
      doc.setTextColor(30);
      doc.text("Summary", 14, finalY + 12);
      doc.setFontSize(10);
      doc.setTextColor(80);
      const summaryLines = doc.splitTextToSize(result.explanation, 180);
      doc.text(summaryLines, 14, finalY + 19);

      doc.save(`${mode}-forecast.pdf`);
      toast({ title: "PDF downloaded", description: "Your forecast report was saved as a PDF." });
    } catch (err) {
      toast({
        title: "PDF export failed",
        description: "Something went wrong generating the PDF. Please try again.",
        variant: "destructive",
      });
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="flex flex-wrap items-center gap-2 no-print">
      <Button variant="glass" size="sm" className="gap-1.5" onClick={handleCsv}>
        <Download className="h-3.5 w-3.5" />
        Export CSV
      </Button>
      <Button variant="glass" size="sm" className="gap-1.5" onClick={handlePdf}>
        <FileText className="h-3.5 w-3.5" />
        Download PDF
      </Button>
      <Button variant="glass" size="sm" className="gap-1.5" onClick={handlePrint}>
        <Printer className="h-3.5 w-3.5" />
        Print
      </Button>
    </div>
  );
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
